<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_addReal" Id="{44fe6edb-c9c1-40ba-a757-3d7869c99e5f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_addReal
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_addReal">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>